default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: blablaslackbot_development

test:
  <<: *default
  database: blablaslackbot_test

production:
  <<: *default
  database: blablaslackbot_production
